/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiktokMediaFileRouteImport } from './routes/tiktok/media/$file'
import { Route as ApiAuthTiktokStartRouteImport } from './routes/api/auth/tiktok/start'
import { Route as ApiAuthTiktokCallbackRouteImport } from './routes/api/auth/tiktok/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokMediaFileRoute = TiktokMediaFileRouteImport.update({
  id: '/tiktok/media/$file',
  path: '/tiktok/media/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTiktokStartRoute = ApiAuthTiktokStartRouteImport.update({
  id: '/api/auth/tiktok/start',
  path: '/api/auth/tiktok/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTiktokCallbackRoute = ApiAuthTiktokCallbackRouteImport.update({
  id: '/api/auth/tiktok/callback',
  path: '/api/auth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/settings': typeof SettingsRoute
  '/tiktok/media/$file': typeof TiktokMediaFileRoute
  '/api/auth/tiktok/callback': typeof ApiAuthTiktokCallbackRoute
  '/api/auth/tiktok/start': typeof ApiAuthTiktokStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/settings': typeof SettingsRoute
  '/tiktok/media/$file': typeof TiktokMediaFileRoute
  '/api/auth/tiktok/callback': typeof ApiAuthTiktokCallbackRoute
  '/api/auth/tiktok/start': typeof ApiAuthTiktokStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/settings': typeof SettingsRoute
  '/tiktok/media/$file': typeof TiktokMediaFileRoute
  '/api/auth/tiktok/callback': typeof ApiAuthTiktokCallbackRoute
  '/api/auth/tiktok/start': typeof ApiAuthTiktokStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compose'
    | '/settings'
    | '/tiktok/media/$file'
    | '/api/auth/tiktok/callback'
    | '/api/auth/tiktok/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compose'
    | '/settings'
    | '/tiktok/media/$file'
    | '/api/auth/tiktok/callback'
    | '/api/auth/tiktok/start'
  id:
    | '__root__'
    | '/'
    | '/compose'
    | '/settings'
    | '/tiktok/media/$file'
    | '/api/auth/tiktok/callback'
    | '/api/auth/tiktok/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposeRoute: typeof ComposeRoute
  SettingsRoute: typeof SettingsRoute
  TiktokMediaFileRoute: typeof TiktokMediaFileRoute
  ApiAuthTiktokCallbackRoute: typeof ApiAuthTiktokCallbackRoute
  ApiAuthTiktokStartRoute: typeof ApiAuthTiktokStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok/media/$file': {
      id: '/tiktok/media/$file'
      path: '/tiktok/media/$file'
      fullPath: '/tiktok/media/$file'
      preLoaderRoute: typeof TiktokMediaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/tiktok/start': {
      id: '/api/auth/tiktok/start'
      path: '/api/auth/tiktok/start'
      fullPath: '/api/auth/tiktok/start'
      preLoaderRoute: typeof ApiAuthTiktokStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/tiktok/callback': {
      id: '/api/auth/tiktok/callback'
      path: '/api/auth/tiktok/callback'
      fullPath: '/api/auth/tiktok/callback'
      preLoaderRoute: typeof ApiAuthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposeRoute: ComposeRoute,
  SettingsRoute: SettingsRoute,
  TiktokMediaFileRoute: TiktokMediaFileRoute,
  ApiAuthTiktokCallbackRoute: ApiAuthTiktokCallbackRoute,
  ApiAuthTiktokStartRoute: ApiAuthTiktokStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
